function batch_analyzeWholeBrain

% set up error log
errorLogPath = fullfile(getpref('mriTOMEAnalysis', 'TOME_analysisPath'), '/mriTOMEAnalysis/errorLogs/');
currentTime = clock;
errorLogFilename = ['errorLog_ROIs_', num2str(currentTime(1)), '-', num2str(currentTime(2)), '-', num2str(currentTime(3)), '_', num2str(currentTime(4)), num2str(currentTime(5))];
system(['echo "', 'SubjectID', ',', 'runName', '" > ', [errorLogPath, errorLogFilename]]);

% subjects = {'TOME_3001', ...
% 'TOME_3002', ...
% 'TOME_3003', ...
% 'TOME_3004', ...
% 'TOME_3004', ...
% 'TOME_3005', ...
% 'TOME_3007', ...
% 'TOME_3008', ...
% 'TOME_3009', ...
% 'TOME_3011', ...
% 'TOME_3012', ...
% 'TOME_3013', ...
% 'TOME_3014', ...
% 'TOME_3015', ...
% 'TOME_3016', ...
% 'TOME_3017', ...
% 'TOME_3018', ...
% 'TOME_3019', ...
% 'TOME_3020', ...
% 'TOME_3021', ...
% 'TOME_3022', ...
% 'TOME_3023', ...
% 'TOME_3024', ...
% 'TOME_3025', ...
% 'TOME_3026', ...
subjects = {'TOME_3028', ...
'TOME_3029', ...
'TOME_3030', ...
'TOME_3031', ...
'TOME_3032', ...
'TOME_3033', ...
'TOME_3034', ...
'TOME_3035', ...
'TOME_3036', ...
'TOME_3037', ...
'TOME_3038', ...
'TOME_3039', ...
'TOME_3042'};


%% from each session, download the hcp-struct.zip
for ss = 1:length(subjects)
    subjectID = subjects{ss};
    
    [ runNames ] = getRunsPerSubject(subjectID);
    for rr = 1:length(runNames)
        
        runName = runNames{rr};
        
        fprintf('Now analyzing Subject %s, Run %s\n', subjectID, runName);
        
        %try
            analyzeRestCIFTI(subjectID, runName)            
            system(['echo "', subjectID, ',', runName, '" >> ', [errorLogPath, 'completedRuns_ROI']]);
            
            close all
%         catch
%             system(['echo "', subjectID, ',', runName, '" >> ', [errorLogPath, errorLogFilename]]);
%         end
%         
    end
    savePath = fullfile(getpref('mriTOMEAnalysis', 'TOME_analysisPath'), 'mriTOMEAnalysis', 'correlationMatrices', subjectID);
    saveName = fullfile(savePath, 'average');
    makeAverageCorrelationMatrix({subjectID}, 'saveName', saveName)
    close all
end

end
