function box_plot(inputMatrix)
% This function generates a notched box plot of the velocities for x and y 
% separated by acquisition
%
% Syntax:
%   box_plot(inputMatrix)
%
% Inputs:
%   inputMatrix         - String Array. Generated by the function
%                           read_all_runs
%
% Outputs:
%   none                  - Box Plot. First figure shows mean velocities
%                           for x for each acquistion. Second figure does
%                           the same for y.
%
% Example:  
%   dot_histo(resultsMatrix)

% Pulls in data from inputMatrix
run_x = str2double(inputMatrix(2:size(inputMatrix,1),[2,6,10,14]));
run_y = str2double(inputMatrix(2:size(inputMatrix,1),[4,8,12,16]));

% Generates figure
clf;
nexttile;
boxplot(run_x,'Notch','on');
ylabel("Degrees per second")
xlabel("X")
xticklabels(["Run 1" "Run 2" "Run 3" "Run 4"])

nexttile;
boxplot(run_y,'Notch','on');
ylabel("Degrees per second")
xticklabels(["Run 1" "Run 2" "Run 3" "Run 4"])
xlabel("Y")
end