function dot_histo(inputMatrix)
% This function generates a scatter plot of the mean velocities for x and y
% with color representing the standard deviation
%
% Syntax:
%   dot_histo(inputMatrix)
%
% Inputs:
%   inputMatrix         -   String Array. Generated by the function
%                           read_all_runs
%
% Outputs:
%   none                  - Scatter Plot. Mean of x (dg/s) is in the x-axis
%                           and mean of y (dg/s) is in the y-axis. The
%                           color represents the mean of the standard
%                           deviations of the means of x and y
%
% Example:  
%   dot_histo(resultsMatrix)

% Pulls in mean and standard deviation of runs from inputMatrix
mean_run_x = str2double(inputMatrix(2:size(inputMatrix,1),18));
mean_run_y = str2double(inputMatrix(2:size(inputMatrix,1),20));
std_run_x = str2double(inputMatrix(2:size(inputMatrix,1),19));
std_run_y = str2double(inputMatrix(2:size(inputMatrix,1),21));

all_runs_x = [mean_run_x mean_run_y std_run_x std_run_y];
mean_std = mean([all_runs_x(:,3),all_runs_x(:,4)],2);

% Generates figure
clf;
scatter(all_runs_x(:,1),all_runs_x(:,2),[],mean_std,"filled");
colorbar
xline(0,'--k');
yline(0,'--k');
xlabel("Mean x (dg/s)")
ylabel("Mean y (dg/s)")
end