function analyzeTimeVaryingCorrelation(subjectID, runName, varargin)

%{
subjectID = 'TOME_3005';
runName = 'rfMRI_REST_AP_Run1';
analyzeTimeVaryingCorrelation(subjectID, runName)
%}
%% Input parser
p = inputParser; p.KeepUnmatched = true;

p.addParameter('correlationMethod', 'slidingWindowPearson', @ischar);
p.addParameter('normalizeTimeVaryingCorrelation', false, @islogical);
p.addParameter('windowLength', 50, @isnumeric);
p.addParameter('TR', 800, @isnumeric);

p.parse(varargin{:});

%% Define the connections of interest
homotopicConnections = { ...
    'V3d_lh+V3v_lh', ...
    'V2d_lh+V2v_lh', ...
    'V1d_lh+V1v_lh', ...
    'V3d_rh+V3v_rh', ...
    'V2d_rh+V2v_rh', ...
    'V1d_rh+V1v_rh', ...
    'V3d_lh+V3d_rh', ...
    'V3v_lh+V3v_rh', ...
    'V3v_lh+V3d_rh', ...
    'V3d_lh+V3v_rh', ...
    'V2d_lh+V2d_rh', ...
    'V2v_lh+V2v_rh', ...
    'V2v_lh+V2d_rh', ...
    'V2d_lh+V2v_rh', ...
    'V1d_lh+V1d_rh', ...
    'V1v_lh+V1v_rh', ...
    'V1v_lh+V1d_rh', ...
    'V1d_lh+V1v_rh', ...
    };
hierarchicalConnections = { ...
    'V3v_lh+V2v_lh', ...
    'V3v_lh+V1v_lh', ...
    'V2v_lh+V1v_lh', ...
    'V3d_lh+V2d_lh', ...
    'V3d_lh+V1d_lh', ...
    'V2d_lh+V1d_lh', ...
    'V3v_rh+V2v_rh', ...
    'V3v_rh+V1v_rh', ...
    'V2v_rh+V1v_rh', ...
    'V3d_rh+V2d_rh', ...
    'V3d_rh+V1d_rh', ...
    'V2d_rh+V1d_rh', ...
    };
backgroundConnections = { ...
    'V3v_lh+V2d_lh', ...
    'V3v_lh+V1d_lh', ...
    'V2v_lh+V3d_lh', ...
    'V2v_lh+V1d_lh', ...
    'V1v_lh+V3d_lh', ...
    'V1v_lh+V2d_lh', ...
    'V3v_rh+V2d_rh', ...
    'V3v_rh+V1d_rh', ...
    'V2v_rh+V3d_rh', ...
    'V2v_rh+V1d_rh', ...
    'V1v_rh+V3d_rh', ...
    'V1v_rh+V2d_rh', ...
    'V3v_rh+V2d_lh', ...
    'V3v_rh+V1d_lh', ...
    'V2v_rh+V3d_lh', ...
    'V2v_rh+V1d_lh', ...
    'V1v_rh+V3d_lh', ...
    'V1v_rh+V2d_lh', ...
    'V3v_lh+V2d_rh', ...
    'V3v_lh+V1d_rh', ...
    'V2v_lh+V3d_rh', ...
    'V2v_lh+V1d_rh', ...
    'V1v_lh+V3d_rh', ...
    'V1v_lh+V2d_rh', ...
    };

allConnections = {homotopicConnections{:}, hierarchicalConnections{:}, backgroundConnections{:}};
connectionTypes = [];
for aa = 1:length(homotopicConnections)
    connectionTypes{end+1} = 'homotopic';
end
for bb = 1:length(hierarchicalConnections)
    connectionTypes{end+1} = 'hierarchical';
end
for cc = 1:length(backgroundConnections)
    connectionTypes{end+1} = 'background';
end






%% Load up data about this run

% load the time series
timeSeriesPath = fullfile(getpref('mriTOMEAnalysis', 'TOME_analysisPath'), 'mriTOMEAnalysis', 'meanV1TimeSeries', subjectID);
load(fullfile(timeSeriesPath, [runName, '_timeSeriesCIFTI'])); % loads up a struct named meanTimeSeries

% create time base
maskNames = fieldnames(meanTimeSeries);
TR = p.Results.TR;
timebase = 0:TR:TR*length(meanTimeSeries.(maskNames{1})) - TR;

%% Loop over connections and calculate time varying correlation
timeVaryingCorrelations = [];
for ii = 1:length(allConnections)
    splitConnections = strsplit(allConnections{ii}, '+');
    regionOne = splitConnections{1};
    regionTwo = splitConnections{2};
    
    timeVaryingCorrelations{end+1} = calculateTimeVaryingCorrelation(meanTimeSeries.([regionOne, '_mask']), meanTimeSeries.([regionTwo, '_mask']), p.Results.windowLength, 'correlationMethod', p.Results.correlationMethod, 'normalizeTimeVaryingCorrelation', p.Results.normalizeTimeVaryingCorrelation);
    
end

%% Get pupil time series
[ covariates ] = makeEyeSignalCovariates(subjectID, runName);
pupilStruct = [];
% resample the pupil data to the same temporal resolution as the BOLD data
pupilStruct.timebase = covariates.timebase;
pupilStruct.values = covariates.pupilDiameterConvolved;
temporalFit = tfeIAMP('verbosity','none');
pupilStruct = temporalFit.resampleTimebase(pupilStruct, timebase, 'resampleMethod', 'resample');

%% Plot to summarize
plotFig = figure; hold on;

for ii = 1:length(timeVaryingCorrelations)
    
    % determine which subplot we're adding to
    if strcmp(connectionTypes{ii}, 'homotopic')
        subplotValue = 1;
    elseif strcmp(connectionTypes{ii}, 'hierarchical')
        subplotValue = 2;
    elseif strcmp(connectionTypes{ii}, 'background')
        subplotValue = 3;
    end
    subplot(1,3,subplotValue); hold on;
    
    % do the plotting
    plot(pupilStruct.values, timeVaryingCorrelations{ii}, '.');
    
end
ax1 = subplot(1,3,1);
title('Homotopic')
xlabel('Pupil Diameter Convolved (mm)');
ylabel(p.Results.correlationMethod);

ax2 = subplot(1,3,2);
title('Hierarchical')
xlabel('Pupil Diameter Convolved (mm)');
ylabel(p.Results.correlationMethod);

ax3 = subplot(1,3,3);
title('Background')
xlabel('Pupil Diameter Convolved (mm)');
ylabel(p.Results.correlationMethod);

linkaxes([ax1, ax2, ax3]);

end